version: "3.7"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio
    container_name: portfolio
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./site.conf:/etc/nginx/conf.d/site.conf

